import Image, { type ImageProps } from 'next/image';
import { IMAGES, type ImageKey } from '@/content/images';
import type { Locale } from '@/lib/i18n/config';
import { cn } from '@/lib/utils';

interface SiteImageProps extends Omit<ImageProps, 'src' | 'alt' | 'width' | 'height'> {
  image: ImageKey;
  locale: Locale;
  /** Override alt when the surrounding content supplies better context. */
  alt?: string;
}

/**
 * Image slot bound to content/images.ts. Every entry has fixed intrinsic
 * dimensions so the layout never shifts, and a locale-aware alt.
 * Placeholder assets are generated by `npm run assets:placeholders` and
 * should be replaced with final photography of the same aspect ratio.
 */
export function SiteImage({ image, locale, alt, className, sizes, priority, ...rest }: SiteImageProps) {
  const def = IMAGES[image];
  return (
    <Image
      src={def.src}
      alt={alt ?? def.alt[locale]}
      width={def.width}
      height={def.height}
      sizes={sizes ?? def.sizes}
      priority={priority ?? def.priority}
      placeholder={def.blurDataURL ? 'blur' : 'empty'}
      blurDataURL={def.blurDataURL}
      className={cn('h-auto w-full', className)}
      {...rest}
    />
  );
}
