export const form = {
  steps: ['What you need', 'About your request', 'Your details'],
  stepLabel: 'Step',
  next: 'Continue',
  back: 'Back',
  submit: 'Submit assessment request',
  submitting: 'Submitting…',
  fields: {
    service: 'What do you need help with?',
    serviceOptions: {
      debt: { label: 'Debt collection', hint: 'Overdue invoices, receivables or amounts owed to you' },
      formation: { label: 'Company formation', hint: 'Setting up or restructuring a company in Qatar' },
      government: { label: 'Government transactions', hint: 'Registrations, renewals, documents and PRO work' },
    },
    name: 'Full name',
    companyType: 'I am enquiring as',
    companyTypeOptions: { company: 'A company', individual: 'An individual' },
    companyName: 'Company name',
    phone: 'Phone / WhatsApp number',
    phonePlaceholder: '+974 5XXX XXXX',
    email: 'Email address',
    debtCategory: 'Type of receivable',
    debtCategoryOptions: {
      commercial_invoices: 'Commercial invoices / B2B receivables',
      contract_balance: 'Contract or project balance',
      rent_service_fees: 'Rent or service fees',
      personal_loan: 'Personal loan or private agreement',
      instalments: 'Instalment or finance balance',
      other: 'Other',
    },
    amountRange: 'Approximate amount (QAR)',
    amountRangeOptions: {
      under_50k: 'Under 50,000',
      '50k_250k': '50,000 – 250,000',
      '250k_1m': '250,000 – 1,000,000',
      over_1m: 'Over 1,000,000',
      undisclosed: 'Prefer not to say',
    },
    debtAge: 'Age of the overdue balance',
    debtAgeOptions: {
      under_30: 'Under 30 days',
      '30_60': '30 – 60 days',
      '60_90': '60 – 90 days',
      '90_180': '90 – 180 days',
      over_180: 'More than 180 days',
    },
    businessActivity: 'Business activity you intend to licence',
    businessActivityPlaceholder: 'e.g. trading in building materials, IT consultancy, contracting',
    governmentTransactionType: 'Type of transaction',
    governmentTransactionOptions: {
      registration_licence: 'Commercial registration or trade licence',
      renewal_amendment: 'Renewal, amendment or cancellation',
      labour_recruitment: 'Labour or recruitment file',
      visa_residence: 'Visa or residence procedure',
      attestation: 'Document attestation',
      other: 'Other',
    },
    timeline: 'When do you need this done?',
    timelineOptions: {
      urgent: 'Urgent — there is a deadline',
      within_month: 'Within a month',
      within_quarter: 'Within three months',
      exploring: 'Still exploring options',
    },
    preferredContact: 'Preferred way to contact you',
    preferredContactOptions: { phone: 'Phone', whatsapp: 'WhatsApp', email: 'Email' },
    message: 'Short description (optional)',
    messagePlaceholder: 'A sentence or two about the situation. Please do not include identity documents or bank details.',
    consent: 'I agree that Ammon Qatar may store these details and contact me about this enquiry, as described in the Privacy Policy.',
    consentLabel: 'Consent',
    consentLink: 'Privacy Policy',
  },
  errors: {
    summary: 'Please correct the following:',
    required: 'This field is required.',
    name: 'Please enter your full name (2–80 characters).',
    companyName: 'Please enter the company name.',
    phone: 'Please enter a valid phone number, e.g. +974 5XXX XXXX.',
    email: 'Please enter a valid email address.',
    select: 'Please choose an option.',
    activity: 'Please describe the activity in a few words.',
    message: 'Please keep the description under 1,000 characters.',
    consent: 'Please confirm you agree to be contacted.',
    rateLimited: 'Too many submissions from this connection. Please try again in a few minutes or contact us directly.',
    server: "We could not submit your request. Please try again, or contact us by phone or WhatsApp.",
  },
  success: {
    heading: 'Request received',
    body: 'Thank you. Your request has been recorded and a member of the team will contact you using your preferred method.',
    reference: 'Your reference',
    next: 'What happens next',
    steps: [
      'We review your summary and any obvious gaps.',
      'We contact you to confirm details and request only the documents needed.',
      'You receive a written assessment and a recommended approach.',
    ],
    whatsapp: 'Continue on WhatsApp',
    home: 'Back to home',
  },
  privacyNote: 'Do not include identity documents, bank details or other sensitive data in this form.',
};

export type FormContent = typeof form;
